### ISSUE TITLE
Fitting LDS with no dynamics fails

### ISSUE THREAD

**Issue by bantin** [slinderman/ssm#73]
The following combination of settings fails for fitting an LDS:
`dynamics = none, emissions = studentst, method = svi, posterior = mf`

This is the traceback:

```
Traceback (most recent call last):
  File "/Users/Bantin/anaconda3/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/tests/test_lds.py", line 480, in test_lds_sample_and_fit
    fit_lds.fit(y, method=method, variational_posterior=posterior, alpha=0)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/util.py", line 108, in wrapper
    return f(self, datas, inputs=inputs, masks=masks, tags=tags, **kwargs)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/lds.py", line 857, in fit
    self.initialize(datas, inputs, masks, tags)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/util.py", line 108, in wrapper
    return f(self, datas, inputs=inputs, masks=masks, tags=tags, **kwargs)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/lds.py", line 171, in initialize
    self.emissions.initialize(datas, inputs, masks, tags)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/util.py", line 108, in wrapper
    return f(self, datas, inputs=inputs, masks=masks, tags=tags, **kwargs)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/emissions.py", line 495, in initialize
    pca = self._initialize_with_pca(datas, inputs=inputs, masks=masks, tags=tags)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/util.py", line 108, in wrapper
    return f(self, datas, inputs=inputs, masks=masks, tags=tags, **kwargs)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/emissions.py", line 190, in _initialize_with_pca
    pca, xs, ll = pca_with_imputation(self.D, resids, masks, num_iters=num_iters)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/preprocessing.py", line 36, in pca_with_imputation
    x = pca.fit_transform(data)
  File "/Users/Bantin/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/pca.py", line 360, in fit_transform
    U, S, V = self._fit(X)
  File "/Users/Bantin/anaconda3/lib/python3.7/site-packages/sklearn/decomposition/pca.py", line 382, in _fit
    copy=self.copy)
  File "/Users/Bantin/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 542, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/Users/Bantin/anaconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 49, in _assert_all_finite
    if is_float and (np.isfinite(_safe_accumulator_op(np.sum, X))):
  File "/Users/Bantin/anaconda3/lib/python3.7/site-packages/sklearn/utils/extmath.py", line 688, in _safe_accumulator_op
    result = op(x, *args, **kwargs)
  File "<__array_function__ internals>", line 6, in sum
  File "/Users/Bantin/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2182, in sum
    initial=initial, where=where)
  File "/Users/Bantin/anaconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
FloatingPointError: invalid value encountered in reduce
```

**Comment by bantin** [comment]
This was an effect of a typo in `StudentsTEmissionsMixin` which was causing NaNs in the sampled data. Fixed in 38280ec.
