### ISSUE TITLE
Newton step fails for Students T DOF Parameter

### ISSUE THREAD

**Issue by bantin** [slinderman/ssm#80]
Reproducer:

```python

import ssm
from ssm.util import SEED
import autograd.numpy as np
np.random.seed(seed=SEED)
true_lds = ssm.SLDS(15, 3, 10, transitions="nn_recurrent", dynamics="diagonal_t", emissions="studentst")
z, x, y = true_lds.sample(100)

new_lds = ssm.SLDS(15, 3, 10, transitions="nn_recurrent", dynamics="diagonal_t", emissions="studentst")
new_lds.fit(y, method="svi", variational_posterior="mf", num_init_iters=2)
```

Traceback:

```python
Traceback (most recent call last):
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/quick_test.py", line 9, in <module>
    new_lds.fit(y, method="svi", variational_posterior="mf", num_init_iters=2)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/util.py", line 110, in wrapper
    return f(self, datas, inputs=inputs, masks=masks, tags=tags, **kwargs)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/lds.py", line 856, in fit
    self.initialize(datas, inputs, masks, tags, num_iters=num_init_iters)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/util.py", line 110, in wrapper
    return f(self, datas, inputs=inputs, masks=masks, tags=tags, **kwargs)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/lds.py", line 184, in initialize
    method="em", num_iters=num_iters)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/util.py", line 110, in wrapper
    return f(self, datas, inputs=inputs, masks=masks, tags=tags, **kwargs)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/hmm.py", line 480, in fit
    return _fitting_methods[method](datas, inputs=inputs, masks=masks, tags=tags, **kwargs)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/hmm.py", line 449, in _fit_em
    self.observations.m_step(expectations, datas, inputs, masks, tags, **observations_mstep_kwargs)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/observations.py", line 1376, in m_step
    self._m_step_nu(expectations, datas, inputs, masks, tags)
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/observations.py", line 1475, in _m_step_nu
    self._log_nus[k] = np.log(generalized_newton_studentst_dof(E_taus[k], E_logtaus[k]))
  File "/Users/bantin/Documents/Linderman-Shenoy/ssm/ssm/regression.py", line 462, in generalized_newton_studentst_dof
    assert a > 0 and b < 0, "generalized_newton_studentst_dof encountered invalid values of a,b"
AssertionError: generalized_newton_studentst_dof encountered invalid values of a,b
```

**Comment by bantin** [comment]
@slinderman  I'm thinking maybe 4ce740065346 might address this. Could you take a look and let me know what you think? It just calls scipy.minimize_scalar if the modified newton method fails. It seems like it tends to fail when E_tau and E_logtau are very small, but I haven't found a good way around this.

**Comment by slinderman** [comment]
You were right, it fails when those inputs are small, which happens when there are very few observations of the Student's t distribution.  I was able to avoid this failure by adding a weak prior to nu.  Fixed in https://github.com/slinderman/ssm/commit/32e194a502710d588c8c7dd8d6d6efca4d81ff6f.
